server:
  port: 1080
spring:
  datasource:
    url: jdbc:mysql://10.26.4.28:3306/yz_itiche_com?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: root
  redis:
    host: 10.26.4.28
    port: 6379
logging:
  level:
    root: info
  file:
    path: ./logs
    max-size: 10MB
    max-history: 30
    total-size-cap: 1024MB
